/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.*;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

import org.example.controller.ElevatorController;
import org.example.model.Elevator;
import org.example.model.Person;
import org.example.view.ElevatorView;

public class App {

    public static void main(String[] args) {
        final BlockingQueue<Person> peopleUsingElevator = new LinkedBlockingQueue<>();

        JFrame frame = new JFrame("Elevator Simulator");
        frame.setSize(800, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        Elevator elevator = new Elevator();
        ElevatorView view = new ElevatorView();
        ElevatorController elevatorController = new ElevatorController(
                elevator, view, peopleUsingElevator);

        frame.getContentPane().add(view);
        frame.setVisible(true);

        new Thread(new PeopleUsingElevator(peopleUsingElevator)).start();
        new Thread(elevatorController).start();
    }
}
